### ISSUE TITLE
Package does not seem to work on Laravel 8.0

### ISSUE THREAD

**Issue by DevelopmentNightmare** [cnviradiya/laravel-filepond#1]
Error message:

Your requirements could not be resolved to an installable set of packages.

 - Installation request for laravel/framework ^8.0 -> satisfiable by laravel/framework[8.x-dev, v8.0.0, v8.0.1, v8.0.2, v8.0.3, v8.0.4, v8.1.0, v8.10.0, v8.11.0, v8.2.0, v8.3.0, v8.4.0, v8.5.0, v8.6.0, v8.7.0, v8.7.1, v8.8.0, v8.9.0].

Is there something I can do to fix this?

**Comment by cnviradiya** [comment]
@Dynalogical Thanks for the reporting the issue.
Sure - If you have any fixes please generate a PR. I will review it and merge it. else I will add the support for the Laravel 8.X later on
